version: '3.2'

services:
  
  postgres:
    container_name: ${PROJECT_NAME}_postgres
    build:
      context: others/postgres/
    environment:
      POSTGRES_DB: "dspace"
      POSTGRES_USER: "dspace"
      POSTGRES_PASSWORD: "dspace"
    volumes:
      - /var/lib/postgresql/data
      - ./others/postgres/dumps/dspace:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    networks:
      - docker-elk_default

  pgadmin4:
      container_name: ${PROJECT_NAME}_pgadmin
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: "user@dspace.com"
          PGADMIN_DEFAULT_PASSWORD: "dspace"
      ports:
      - "82:80"
      networks:
        - docker-elk_default
         
networks:
  docker-elk_default:
    external: true
